#!/usr/bin/env bash
# Regenerates internal/stinstall/pins.go (the SHA-256 pins of the Syncthing
# release that SyncThing V2 downloads when Syncthing is missing) and sets
# brand.BootstrapSyncthing to the same version.
#
# Usage: scripts/update-syncthing-pin.sh vX.Y.Z
#
# The checksums come from the release's sha256sum.txt.asc and are used only
# after its signature verifies against build/syncthing-release-key.asc.
#
# Release key: "Syncthing Release Management <release@syncthing.net>",
# rsa4096, created 2024-11-24, fetched from https://syncthing.net/release-key.txt
#   Fingerprint: FBA2 E162 F2F4 4657 B38F  0309 E566 5F9B D597 0C47
# Cross-checks done when the key was added:
#   - The copy in Syncthing's website repository
#     (github.com/syncthing/website, static/release-key.txt, which
#     https://syncthing.net/security/ links as "the release PGP key") is
#     byte-identical to the file served by syncthing.net.
#   - The key carries a valid certification from the previous release key
#     37C8 4554 E7E0 A261 E4F7  6E1E D26E 6ED0 0065 4A3E (D26E6ED000654A3E),
#     the key ID Syncthing's security documentation shows in its
#     "Verifying a Release Signature" example.
#   - Release v2.1.5's sha256sum.txt.asc carries good signatures from both keys.
#
# Needs: bash, curl, gpg, awk, sed, grep, mktemp.

set -euo pipefail

readonly KEY_FPR="FBA2E162F2F44657B38F0309E5665F9BD5970C47" # public release-key fingerprint, not a secret; gitleaks:allow
readonly RELEASES="https://github.com/syncthing/syncthing/releases/download"

die() {
	printf 'update-syncthing-pin: %s\n' "$*" >&2
	exit 1
}

[[ $# -eq 1 ]] || die "usage: $0 vX.Y.Z"
version="$1"
[[ "$version" =~ ^v[0-9]+\.[0-9]+\.[0-9]+(-[0-9A-Za-z.]+)?$ ]] || die "not a release version: $version"

for tool in curl gpg awk sed grep mktemp; do
	command -v "$tool" >/dev/null 2>&1 || die "$tool is required"
done

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
keyfile="$root/build/syncthing-release-key.asc"
out="$root/internal/stinstall/pins.go"
brandfile="$root/internal/brand/brand.go"
[[ -f "$keyfile" ]] || die "missing $keyfile"
[[ -f "$brandfile" ]] || die "missing $brandfile"

work="$(mktemp -d)"
trap 'rm -rf "$work"' EXIT
export GNUPGHOME="$work/gnupg"
mkdir "$GNUPGHOME"
# Git Bash on Windows cannot always set POSIX modes; gpg only warns then.
chmod 700 "$GNUPGHOME" 2>/dev/null || true

# 1. Import the committed key into a throwaway keyring and make sure it is
#    exactly the pinned key, so a swapped key file cannot go unnoticed.
gpg --batch --quiet --import "$keyfile" 2>/dev/null || die "cannot import $keyfile"
primaries="$(gpg --batch --with-colons --fingerprint | awk -F: '/^pub:/ { want = 1; next } want && /^fpr:/ { print $10; want = 0 }')"
[[ "$primaries" == "$KEY_FPR" ]] || die "$keyfile must hold exactly the key $KEY_FPR (found: ${primaries:-none})"

# 2. Download the signed checksum list.
asc="$work/sha256sum.txt.asc"
curl -fsSL --proto '=https' --tlsv1.2 --retry 3 -o "$asc" "$RELEASES/$version/sha256sum.txt.asc" ||
	die "cannot download sha256sum.txt.asc for $version"
[[ "$(grep -c -- '-----BEGIN PGP SIGNED MESSAGE-----' "$asc")" == "1" ]] ||
	die "sha256sum.txt.asc must contain exactly one signed message"

# 3. Verify it. The file may carry further signatures by keys we do not hold
#    (gpg then exits non-zero), so success is decided from the status lines:
#    a VALIDSIG whose primary key is the pinned one, and no BADSIG.
plain="$work/sha256sum.txt"
set +e
gpg --batch --status-fd 3 --output "$plain" --decrypt "$asc" 3>"$work/status" 2>"$work/gpg.log"
set -e
grep -E '^(gpg: +(Signature made|using|Good signature|BAD signature|Can.t check)|Primary key fingerprint)' "$work/gpg.log" || true
if grep -q '^\[GNUPG:\] BADSIG' "$work/status"; then
	die "BAD signature on sha256sum.txt.asc"
fi
awk -v fpr="$KEY_FPR" '$1 == "[GNUPG:]" && $2 == "VALIDSIG" && $NF == fpr { ok = 1 } END { exit !ok }' "$work/status" ||
	die "no valid signature by $KEY_FPR on sha256sum.txt.asc"
[[ -s "$plain" ]] || die "signed content is empty"
echo "Signature by $KEY_FPR verified."

# 4. Pick the bootstrap assets out of the verified text only.
assets=(
	"syncthing-linux-amd64-$version.tar.gz"
	"syncthing-linux-arm64-$version.tar.gz"
	"syncthing-macos-universal-$version.zip"
	"syncthing-windows-amd64-$version.zip"
)
width=0
for a in "${assets[@]}"; do
	if ((${#a} > width)); then
		width=${#a}
	fi
done

tmp="$work/pins.go"
{
	echo '// Code generated by scripts/update-syncthing-pin.sh; DO NOT EDIT.'
	echo
	echo 'package stinstall'
	echo
	echo '// pinnedVersion is the Syncthing release the pins belong to. It must equal'
	echo '// brand.BootstrapSyncthing.'
	printf 'const pinnedVersion = "%s"\n' "$version"
	echo
	echo '// pins maps each bootstrap asset of pinnedVersion to its SHA-256, taken from'
	echo '// the release'"'"'s sha256sum.txt.asc after its signature verified against'
	echo '// build/syncthing-release-key.asc'
	echo '// (key fingerprint FBA2 E162 F2F4 4657 B38F  0309 E566 5F9B D597 0C47).'
	echo 'var pins = map[string]string{'
	for a in "${assets[@]}"; do
		sum="$(awk -v name="$a" '{ n = $2; sub(/^\*/, "", n) } n == name { print $1 }' "$plain")"
		[[ "$sum" =~ ^[0-9a-f]{64}$ ]] || die "no single SHA-256 for $a in sha256sum.txt.asc"
		# gofmt alignment: pad the quoted key and colon to the longest key.
		printf '\t%-*s "%s",\n' "$((width + 3))" "\"$a\":" "$sum"
	done
	echo '}'
} >"$tmp"

if command -v gofmt >/dev/null 2>&1 && [[ -n "$(gofmt -l "$tmp")" ]]; then
	die "generated pins.go is not gofmt-clean"
fi

if [[ -f "$out" ]] && cmp -s "$tmp" "$out"; then
	echo "internal/stinstall/pins.go is up to date for $version."
else
	cat "$tmp" >"$out"
	echo "Wrote internal/stinstall/pins.go for $version."
fi

# 5. Keep brand.BootstrapSyncthing in step with the pins.
pattern='^([[:space:]]*BootstrapSyncthing[[:space:]]*=[[:space:]]*)"[^"]*"'
[[ "$(grep -cE "$pattern" "$brandfile")" == "1" ]] || die "cannot find BootstrapSyncthing in $brandfile"
if ! grep -qE "^[[:space:]]*BootstrapSyncthing[[:space:]]*=[[:space:]]*\"$version\"" "$brandfile"; then
	sed -E "s/$pattern/\\1\"$version\"/" "$brandfile" >"$work/brand.go"
	cat "$work/brand.go" >"$brandfile"
	echo "Set brand.BootstrapSyncthing to $version."
fi
