// Code generated by scripts/update-syncthing-pin.sh; DO NOT EDIT.

package stinstall

// pinnedVersion is the Syncthing release the pins belong to. It must equal
// brand.BootstrapSyncthing.
const pinnedVersion = "v2.1.5"

// pins maps each bootstrap asset of pinnedVersion to its SHA-256, taken from
// the release's sha256sum.txt.asc after its signature verified against
// build/syncthing-release-key.asc
// (key fingerprint FBA2 E162 F2F4 4657 B38F  0309 E566 5F9B D597 0C47).
var pins = map[string]string{
	"syncthing-linux-amd64-v2.1.5.tar.gz":  "3d222b609f7ab2944e02748cb10488b4160d446b49e0eafc107ef2a525ab3486",
	"syncthing-linux-arm64-v2.1.5.tar.gz":  "3666f3069feeee3651e185f867759206059755101797bdd69ea5317610130855",
	"syncthing-macos-universal-v2.1.5.zip": "e4ed8fc7cd7570f77293783adbccacd1abc822a5905a50e90ab38dc55a813c54",
	"syncthing-windows-amd64-v2.1.5.zip":   "39571e4d0900c2a2cab14c0b170f49751340a869e49734ccc8079d9b98a7974b",
}
